---
title: "Write a function"
author: "Ke Xu"
date: "11/14/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

set.seed(1)
```

## Z scores

```{r}
x_vec = rnorm(25, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)

# If I want to repeat that function:
z_scores = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } 
  else if (length(x) == 1) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
  
  z = (x - mean(x)) / sd(x)
  return(z)
  
}
z_scores(x = x_vec) # z_scores(x_vec)

y_vec = rnorm(40, mean = 12, sd = .3)

z_scores(x = y_vec)
```

How great it is?
```{r, error=TRUE}
z_scores(3)
```


## Multiple outputs

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  output_df = 
    tibble(
      mean = mean_x,
      sd = sd_x
    )
  
  return(output_df)
}
```


## Multiple inputs

```{r}
sim_mean_sd = function(n, mu, sigma) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  
  sim_data %>% 
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
}

sim_mean_sd(30,4,3)
```


## Napoleon

```{r}
read_page_reviews = function(url) {
  
  html = read_html(url)
  
  review_titles = 
    html %>%
    html_nodes(".a-text-bold span") %>%
    html_text()
  
  review_stars = 
    html %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("^\\d") %>%
    as.numeric()
  
  review_text = 
    html %>%
    html_nodes(".review-text-content span") %>%
    html_text() %>% 
    str_replace_all("\n", "") %>% 
    str_trim()
  
  tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
}

url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
vec_urls = str_c(url_base, 1:5)

dynamite_reviews = bind_rows(
  read_page_reviews(vec_urls[1]),
  read_page_reviews(vec_urls[2]),
  read_page_reviews(vec_urls[3]),
  read_page_reviews(vec_urls[4]),
  read_page_reviews(vec_urls[5])
)

dynamite_reviews
```


# Class 2

## Lists

```{r}
l = 
  list(
  vec_numeric = 5:8,
  vec_logical = c(TRUE, FALSE),
  summary = summary(rnorm(1000, mean = 5, sd = 3))
)

l[[1]] # see the first line of the list
l[["summary"]] # see "summary" line (line 3)
l$summary # the same as [[]]
```


## List of normals

```{r}
list_norms = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(20, 0, 5),
    c = rnorm(20, 10, .2),
    d = rnorm(20, -3, 1)
  )

mean_and_sd(list_norms[[1]]) # use the function we previously make
```


## For loop

```{r}
output = vector("list", length = 4) # set up an empty list

output[[1]] = mean_and_sd(list_norms[[1]])

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norms[[i]])
}
```

Let's use map instead...

```{r}
map(list_norms, mean_and_sd)

map_output = map(list_norms, median) # you can put "make sense" object like median 
map(list_norms, IQR)
map(list_norms, summary)

map_output[[1]]
```

## List columns

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norms
  )

listcol_df %>% pull(name)

listcol_df$samp[[1]]

mean_and_sd(listcol_df$samp[[1]])

map(listcol_df$samp, mean_and_sd) # use map to calculate all values in 'samp'
```


## Nested data

```{r}
# Input data

weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

Nest data within location
```{r}
weather_nested = nest(weather_df, data = date:tmin) # nest all data 

weather_nested %>% 
  filter(name == "CentralPark_NY") %>% 
  pull(data)

# unnest 
unnest(weather_nested, data)
# we can also pipe:
weather_nested %>% 
  unnest(data)
```

## Linear regression

```{r}
 lm(tmax ~ tmin, data = weather_nested$data[[1]])

# a function
weather_lm = function(df) {
  lm(tmax ~ tmin, data = df)
}

weather_lm(weather_nest$data[[1]])
```

```{r}
map(weather_nested$data, weather_lm)

weather_df %>% 
  mutate(lm_results = map(data, weather_lm))
```




















